//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВКР_общежитие
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order1
    {
        public int ID { get; set; }
        public Nullable<int> id_Заказчик { get; set; }
        public Nullable<int> id_Типа { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> id_Единица_Измерения { get; set; }
        public Nullable<int> Кол_во { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual StorageType StorageType { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
