//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВКР_общежитие
{
    using System;
    using System.Collections.Generic;
    
    public partial class VozvrNakl
    {
        public int ID { get; set; }
        public Nullable<int> id_Организации { get; set; }
        public string Нарушение { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> id_Товарной_накладной { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
